&bbu_params
  bbu_param%lat_filename = 'oneturn_lat.bmad'
  bbu_param%keep_overlays_and_groups = False
  bbu_param%simulation_turns_max = 500
  bbu_param%elname = 'T1'
  bbu_param%hybridize = True
  bbu_param%nrep = 5
  bbu_param%limit_factor = 3
  bbu_param%keep_all_lcavities = False
  bbu_param%ran_gauss_sigma_cut = 3
  bbu_param%nstep = 50
  bbu_param%current = 1.000
  bbu_param%ran_seed = 100
  bbu_param%rel_tol = 0.001
  bbu_param%lat2_filename = ''
  bbu_param%bunch_freq = 1300000000.0
/
