!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_svn_version = "54809"
character(*), parameter :: tao_svn_date = "2023-07-01 15:46:45"
end module
