!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_svn_version = "54810"
character(*), parameter :: tao_svn_date = "2023-07-01 16:28:12"
end module
