#!/bin/bash

# Script to define common build linker flags
# This script is invoked by either the ACC Release or 
# Distribution environments.
# No Package Specific settings are in this file.
# Exit Codes found in /usr/include/sysexits.h

#set -x

# Set Plot Library Linker Flags
if [ "${ACC_PLOT_PACKAGE}" == "plplot" ] ; then
    export PLOT_LINK_LIBS="plplot plplotcxx plplotf95 csirocsa qsastime"
    export PLOT_LINK_FLAGS="-lplplot -lplplotcxx -lplplotf95 -lcsirocsa -lqsastime -lpthread"
else
    export PLOT_LINK_LIBS="pgplot"
    export PLOT_LINK_FLAGS="-lpgplot"
fi

