#!/bin/csh
##############################################
# linux only
# This script tunes environment variables for intel
# compiler agains built cesr library. Usage:
#               source cesr_intel_set <library>
# where <library> is CESR release library
#          Example:
#               source cesr_intel_set cesr_2006_0313_intel
#
#if <library> is empty (no argument)
#then it will be tuned against devel (devel->devel_intel)
#                    
###############################################
source /nfs/opt/intel_fc_80/bin/ifortvars.csh
if ( $#argv == 0  ) then
 setenv CESRF90 intel; setenv CESRLIB devel;source /home/cesrulib/bin/cesrdef
else
 setenv CESRF90 intel; setenv CESRLIB $1;source /home/cesrulib/bin/cesrdef
endif

