#!/bin/sh
##############################################
# linux only
# This script tunes environment variables for intel
# compiler agains built cesr library. Usage:
#               . cesr_intel_set <library>
# where <library> is CESR release library
#          Example:
#               . cesr_intel_set cesr_2006_0313_intel
#
#if <library> is empty (no argument)
#then it will be tuned against devel  (devel->devel_intel)
#                    
###############################################
# . /nfs/opt/intel_fc_80/bin/ifortvars.sh
if ( [ $# -eq 0 ] ) then
 CESRF90=intel; CESRLIB=devel;. /home/cesrulib/bin/accdefs
else
  CESRF90=intel; CESRLIB=$1;. /home/cesrulib/bin/accdefs
fi
