#!/bin/sh
#---------------------------------------------------------------
# cesr_to_vms - Script to move a specfied library directory from 
#            Unix to VMS
#
# Usage:  cesr_to_vms <library_directory full path>
#
# Inputs:  library_directory  -  full path to the directory to 
#                                zip and move
#
# Author:  M. Palmer  01/09/02
#
#---------------------------------------------------------------
#
# $Id$
#
# $Log$
# Revision 1.3  2006/11/09 16:10:40  cesrulib
# Script now handles FTPing of source code zip file to VMS on its own.
#
# Revision 1.2  2006/11/07 18:00:27  cesrulib
# No longer performs zipping operation on the solaris machine.
# Some extra output information as well.
#
# Revision 1.1  2004/10/19 19:21:28  cesrulib
# VMS porting.
#
#
#---------------------------------------------------------------
# Inputs
FULL_DIR_NAME=$1

if ( [ $# -ne 1 ] ) then
		echo "[cesr_to_vms]:  Incorrect number of parameters specified.  Exiting!"
		exit 1
fi

# Initializations
DIR_NAME=`basename ${FULL_DIR_NAME}`
#INTEL_LIB_DIR=`dirname ${FULL_DIR_NAME}`
#MAIN_LIB_DIR=`dirname ${INTEL_LIB_DIR}`

#VMS_LIB_DIR=${MAIN_LIB_DIR}/VMS_alpha_hp
#VMS_LOG_DIR=${MAIN_LIB_DIR}/log/VMS_alpha_hp
#VMS_LOG_FILE=${VMS_LOG_DIR}/${DIR_NAME}.build_status

# Remote path on VMS cluster where library archives are kept.
WORKDIR=CESR2f'$'DKB200:[CESR_LIBS.ZIP]

# Now make a copy for transport to VMS
echo "Preparing ${DIR_NAME} for transport to vms"
#cd ${VMS_LIB_DIR}
cd ${FULL_DIR_NAME}

# Zip up the source-tree
#/usr/bin/zip -r ${LIB_NAME} ${LIB_NAME} >> ${VMS_LOG_FILE}
/usr/bin/zip -r ${DIR_NAME} . ${DIR_NAME}
if ( [ ${?} -ne 0 ] ) then
    echo "Zipping operation failed in VMS preparation job!"
    exit 55
fi
echo "Zipping operation complete in VMS preparation job."

# Now ftp the library to the [cesrulib.cesr_libs] area on CESR2f
echo "Transferring file ${DIR_NAME}.zip to VMS machine CESR2f via FTP... "
echo "Destination = ${WORKDIR}"
ftp cesr2f <<EOF
		binary
		cd $WORKDIR
		put ${DIR_NAME}.zip
EOF
ftp_success=${?}

# Notify of completion
if ( [ ${ftp_success} -eq 0 ] ) then
    echo "Transfer of ${DIR_NAME} to CESR2f::${WORKDIR} complete!"
else
    echo "***ERROR! Transfer of ${DIR_NAME} to CESR2F FAILED!" 
    exit 0
fi

