#!/usr/bin/perl
#-*-perl-*-
#
# this program checks dependencies of individual fortan files when
# called from the makefile.



($search_dirs, $local_mods, $mod_out_dir, $prefix, $suffix, $d_file, $f_file)
    =parse_args(\@ARGV);
($needed_incs, $needed_mods, $mods_to_create)
    =get_used_module_names($f_file, $d_file);
if(@{$needed_mods} || @{$needed_incs})
 {
  ($final_module_list, $final_inc_list)
    =find_mods($needed_mods, $search_dirs, $mod_out_dir, $local_mods, $needed_incs);
  $mods_to_create=finalize_mods_to_create($mods_to_create, $mod_out_dir);
  print_d_file($prefix, $f_file, $suffix, $d_file, $mods_to_create, $final_module_list, $final_inc_list);
 }

sub print_empty_d_file
 {
  $d_file=$_[0];
  open(F_out, ">$d_file");
  print F_out ("# DO NOT DELETE\n");
  print "no dependencies to record: $d_file\n"
 }

sub print_d_file
 {
  $prefix            =$_[0];
  $f_file            =$_[1];
  $suffix            =$_[2];
  $d_file            =$_[3];
  $mods_to_create    =$_[4];
  $final_module_list =$_[5];
  $final_inc_list    =$_[6];
  $mods_to_create_var="";
  $final_module_var  ="";
  $final_inc_var     ="";

  foreach $mod (@{$mods_to_create})
   {$mods_to_create_var="$mods_to_create_var $mod";}
  foreach $mod (@{$final_module_list})
   {$final_module_var="$final_module_var $mod.mod";}
  $f_file=~/(\w+)\.\w{1,3}$/;
  $f_file=$1;
  open(F_out, ">$d_file");
  print F_out ("# DO NOT DELETE\n\n");
  foreach $inc (@{$final_inc_list})
   {print F_out ("$prefix$f_file$suffix: $inc\n");}    
  if($final_module_var)
   {print F_out ("$prefix$f_file$suffix$mods_to_create_var: $final_module_var\n");} 
#  print F_out ("\t\@echo reading dependencies from $d_file\n");
  close(F_out);
 }

sub finalize_mods_to_create
 {
  $mods_to_create=$_[0];
  $mod_out_dir   =$_[1];
  foreach $mod (@{$mods_to_create})
   {push(@mods_to_create2,"$mod_out_dir/$mod.mod");}
  return \@mods_to_create2;
 }


sub find_mods
 {
  @final_inc_list   =();
  @final_module_list=();
  $needed_mods      =$_[0];
  $search_dirs      =$_[1];
  $mod_out_dir      =$_[2];
  $local_mods       =$_[3];
  $needed_incs      =$_[4];
  push(@{$needed_mods}, @{$needed_incs});
  MOD: foreach $mod (@ {$needed_mods})
   {
    foreach $local_mod (@ {$local_mods})
     {
      if("$mod.mod" eq $local_mod)
       {
        push(@final_module_list,"$mod_out_dir/$mod");        
        next MOD;
       }
     }
    foreach $dir (@ {$search_dirs})
     {
			$norm_dir=$dir;
			$norm_dir=~s/\/[\w_]+\/\.\.//g;
      if(`find $dir -name $mod.mod -print 2>temp.out`)
       {
        push(@final_module_list,"$dir/$mod");
        next MOD;
       }
      elsif(`find $dir -name $mod -print 2>temp.out`)
       {
        push(@final_inc_list,"$norm_dir/$mod");
        next MOD;
       }
     }
    if($mod=~/\.inc$/)
     {push(@final_inc_list, "$mod_out_dir/$mod");}
    else
     {push(@final_module_list, "$mod_out_dir/$mod");}
    print STDERR "warning: can't find $mod, assuming local.\n";
   }
  `rm -fr temp.out`;
  return (\@final_module_list, \@final_inc_list);
 }


sub get_used_module_names
 {
  $f_filename     =$_[0];
  $d_file         =$_[1];
  @needed_incs    =();
  @mods_to_create =();
  @needed_mods    =();
  @grep_out_inc   =`grep -whi "#include" $f_filename`; 
  @grep_out_mod   =`grep -whi "module" $f_filename | grep -vi " END "`;
  @grep_out_use   =`grep -whi "use" $f_filename`;
  foreach $line (@grep_out_inc)
   {
    if(($line=~/(.*?)#include\s"(\S+?)"/i) && (!($1=~/!/)))
     {push(@needed_incs,$2) unless ($seen{$2}++);}
   }
  foreach $line (@grep_out_mod)
   {
    if(($line=~/^\s*module\s(\S+)/i) && ($1!~/PROCEDURE/i))
     {push(@mods_to_create,lc($1)) unless ($seen{lc($1)}++);}
   }
  foreach $line (@grep_out_use)
   { 
    while($line)
     {
      if(($line=~/^(\s*?)\buse\s+([\w_]+)[\s;,](.+)/i) || ($line=~/^(\s*?)\buse\s+([\w_]+)$/i))
       {
        push(@needed_mods,lc($2)) unless ($seen{lc($2)}++);
        $line=$3;
       }
      else
       {$line=0;}
     }
   }
  $needed_mods_length=@needed_mods;
  $needed_incs_length=@needed_incs;
  if((!$needed_mods_length)&&(!$needed_incs_length))
   {
    print_empty_d_file($d_file);
    return (0,0);
   }
  return (\@needed_incs, \@needed_mods, \@mods_to_create);
 }
  


sub parse_args
 {
  $arguments    =$_[0];
  @Is           =();
  @MOD          =();
  @makedep_args =();
  foreach $argument (@{$arguments})
   {
    if($argument=~/^-I(.+)/)
     {
      push(@Is,$1);
      push(@makedep_args," -I\"$1\"");
     }
    elsif($argument=~/^-MOD(.+)/)
     {push(@MOD,(split /\s/,$1));}
    elsif($argument=~/^-MP(.+)/)
     {$MP=$1;}
    elsif($argument=~/^-PRE(.+)/)
     {
      $PRE=$1;
      push(@makedep_args," -p\"$1\"");   
     }
    elsif($argument=~/^-SUF(.+)/)
     {
      $SUF=$1;
      push(@makedep_args," -o\"$1\"");
     }
    elsif($argument=~/^-f(.+)/)
     {
      $f=$1;
      push(@makedep_args," -f\"$1\"");
     }
    else
     {
      $f_filename=$argument;
      push(@makedep_args," \"$argument\"");
     }#=~/(\w+)\.\w{1,3}$/;}
   }
  if(!($f))
	 {$f="depend";}
  `makedepend @makedep_args`;
  return (\@Is, \@MOD, $MP, $PRE, $SUF, $f, $f_filename);
 }






