#!/bin/sh
#--------------------------------------------------------------
# common_env_setup
# -----------------
#
# Meant to be sourced into the environment of the calling
# script.
#
# Provides variable definitions:
#
#    TEMP_OS_ID
#    TEMP_ARCH_ID
#    TEMP_OS_ARCH_ID
#    TEMP_SETUP_F90
#--------------------------------------------------------------

#--------------------------------------------------------------
# Obtain information about OS and machine architecture.
#--------------------------------------------------------------
TEMP_OS="`uname`"
TEMP_ARCH="`uname -m`"
TEMP_OS_ARCH="${TEMP_OS}_${TEMP_ARCH}"


#--------------------------------------------------------------
# Set the default fortran compiler.
#
# ifort     default on  Linux_i686 
# gfortran
#--------------------------------------------------------------
case ${TEMP_OS_ARCH} in

    "Linux_i686" )
	#TEMP_FC="intel";;
	TEMP_FC="ifort";;

    "Linux_x86_64" )
	#TEMP_FC="intel";;
	TEMP_FC="ifort";;

    "Darwin_i386" )
	TEMP_FC="gfortran";;

    * )
	TEMP_FC="gfortran";;
esac

