#!/bin/bash

# Order here matters.
DIRLIST="xsif PGPLOT lapack-3.4.2 gsl fgsl forest recipes_f-90_LEPP sim_utils bmad tao cpp_bmad_interface examples cesr_utils bmadz bsim"

for DIR in ${DIRLIST}
do
  cd ${DIST_BASE_DIR}/${DIR};
  echo -e "\nBuilding directory: ${DIR}\n"
  mk -j ${ACC_SET_GMAKE_JOBS} ${1}
  if ( [ ${?} != 0 ] ) then
    echo -e "\nError in distribution build.\n"
    exit 1
  fi
done

cd ${DIST_BASE_DIR}

