#!/bin/bash

# Script to build the debug version of the distribution.

# Order here matters.
DIRLIST="xsif PGPLOT lapack gsl fgsl forest recipes_f-90_LEPP sim_utils bmad tao cpp_bmad_interface examples cesr_utils bmadz bsim"

for DIR in ${DIRLIST}
do
  cd ${DIST_BASE_DIR}/${DIR};
  echo -e "\nBuilding directory: ${DIR}\n"
  mkd ${1}
  if ( [ ${?} != 0 ] ) then
    echo -e "\nError in distribution build.\n"
    exit 1
  fi
done

cd ${DIST_BASE_DIR}

