#!/bin/bash

# Order here matters.
DIRLIST="xsif PGPLOT lapack gsl fgsl forest recipes_f-90_LEPP sim_utils xraylib bmad tao cpp_bmad_interface examples bsim util_programs regression_tests"

if [ "${ACC_PLOT_PACKAGE}" == "plplot" ] ; then DIRLIST="plplot ${DIRLIST}" ; fi 

for DIR in ${DIRLIST}
do
  cd ${DIST_BASE_DIR}/${DIR};
  echo -e "\nBuilding directory: ${DIR}\n"
  mk -j ${ACC_SET_GMAKE_JOBS} ${1}
  if ( [ ${?} != 0 ] ) then
    echo -e "\nError in distribution build.\n"
    exit 1
  fi
done

cd ${DIST_BASE_DIR}

