#!/bin/bash

# Script to build the debug version of the distribution.

# Order here matters.
DIRLIST="xsif PGPLOT forest recipes_f-90_LEPP sim_utils bmad cesr_utils bmadz tao bsim examples"

for DIR in ${DIRLIST}
do
  cd ${DIST_BASE_DIR}/${DIR};
  echo "Building directory: ${DIR}"
  if ( [ "${DIR}" == "PGPLOT" ] ) then
    ./acc_build -debug
  else
    mkd ${1}
  fi
  if ( [ ${?} != 0 ] ) then
    echo "Error in distribution build."
    exit 1
  fi
done

cd ${DIST_BASE_DIR}



