#!/usr/bin/perl
#packages dir includes PGPLOT cfortran forest recipes_c-ansi recipes_f-90

use FileHandle;

$master_dir="/home/cesrulib/cesr_libs";
$recent_pkg=$ENV{CESR_PKG};
$linux="";
$whole=0;
@is_linux=`uname`;
if($is_linux[0]=~/inux/)
 {$linux="_lnx";}

open (STDOUT,">buildlog_$ARGV[0]");
open (STDERR,">&STDOUT");

autoflush STDOUT 1;
autoflush STDERR 1;

if (!$ARGV[0])
 {die ("\nincorrect arguments\n");}
if ($ARGV[0]=~/[0-9]{4}_[0-9]{4}/)
 {
  $whole=1;
  makewholerelease($master_dir, $ARGV[0]);
 }
elsif ($ARGV[0] eq "PGPLOT")
 {sure(); makePGPLOT($recent_pkg);}
elsif ($ARGV[0] eq "cfortran")
 {sure(); makecfortran($recent_pkg);}
elsif ($ARGV[0] eq "forest")
 {sure(); makeforest($recent_pkg);}
elsif ($ARGV[0] eq "recipes_f-90")
 {sure(); makerecipes_f90($recent_pkg);}
elsif ($ARGV[0] eq "recipes_c-ansi")
 {sure(); makerecipes_cansi($recent_pkg);}

close(STDOUT);
close(STDERR);
if($whole)
 {
  `cp ./buildlog_$ARGV[0] /home/cesrulib/cesr_libs/log/Build/log_$ARGV[0]/`;
 }
else
 {
  `cp ./buildlog_$ARGV[0] /home/cesrulib/cesr_libs/log/log_$ARGV[0]_rebuild`;
 } 


sub sure()
 {
  $recent_pkg=$_[0];
  $library=$_[1];
  print "\nyou are about to rebuild $library in $recent_pkg.  are you sure? (yes/no)[no]\n";
  if(readline(STDIN)!~/yes/)
   {die ("\nrebuild aborted.\n");}
  else
   {print "\nok, here we go....\n";}
 }

sub makewholerelease()
 {
  $master_dir=$_[0];
  $date=$_[1];
  $new_pkg="$master_dir/$date";
  if(-d $new_pkg)
   {die ("\npackage release already exists\n");}
  else
   {
    mkdir($new_pkg);
    mkdir("$new_pkg/lib");
    mkdir("$new_pkg/log");
   }
  makePGPLOT($new_pkg);
  makecfortran($new_pkg);
  makeforest($new_pkg);
  makerecipes_f90($new_pkg);
  makerecipes_cansi($new_pkg);
 }

sub makePGPLOT()
 {
  $pkg_dir=$_[0];
  chdir($pkg_dir);
  if(-d "PGPLOT")
   {
    `rm ./lib/libpg*`;
    `rm -r PGPLOT`;
   }
  `cvs -d \$CESR_CVSROOT co PGPLOT`;
  chdir("./PGPLOT");
  if($linux=~/lnx/)
   {print `makemake . linux g77_gcc`;}
  else
   {print `makemake . osf1 f77_cc`;}
  print `gmake`;
  print `cp libpgplot.a ../lib/libpgplot.a`;
  print `cp libpgplot.a ../lib/libpgplot_g.a`;
 }

sub makecfortran()
 {
  $pkg_dir=$_[0];
  chdir($pkg_dir);
  if(-d "cfortran")
   {`rm -r cfortran`;}
  `cvs -d \$CESR_CVSROOT co cfortran`;
 }

sub makeforest()
 {
  $pkg_dir=$_[0];
  chdir($pkg_dir);
  if(-d "forest")
   {
    chdir("$pkg_dir/forest");
    `gmake clean`;
    chdir($pkg_dir);
    `rm -r forest`;
   }
  `cvs -d \$CESR_CVSROOT co forest`;
  chdir("./forest");
  print `gmake`;
 }

sub makerecipes_f90()
 {
  $pkg_dir=$_[0];
  if($linux=~/lnx/)
   {
    $F90OPTS="";
    $F90OPTS_g="-g";
    $F90="/opt/lf9561/bin/lf95";
   }
  else
   {
    $F90OPTS="-check bounds -check format -check nounderflow -warn declarations -warn argument_checking";
    $F90OPTS_g="-check bounds -check format -check nounderflow -warn declarations -warn argument_checking -g";
    $F90="f90";
   }
  chdir($pkg_dir);
  if(-d "recipes_f-90")
   {
    chdir("$pkg_dir/recipes_f90");
    `gmake clean`;
    chdir($pkg_dir);
    `rm -r recipes_f-90`;
   }
  `cvs -d \$CESR_CVSROOT co recipes_f-90`;
  chdir("./recipes_f-90");  
  print `gmake F90="$F90" NRROOT="$pkg_dir/recipes_f-90" F90OPTS="$F90OPTS" lib`;
  print `cp librecipes_f90.a ../lib/librecipes_f90.a`;
  print `cp *.mod ../modules`;
  print `gmake NRROOT="$pkg_dir/recipes_f-90" clean`;
  print `gmake NRROOT="$pkg_dir/recipes_f-90"  F90="$F90" F90OPTS="$F90OPTS_g" lib`; 
  print `cp librecipes_f90.a ../lib/librecipes_f90_g.a`;
 }

sub makerecipes_cansi()
 {
  $pkg_dir=$_[0];
  chdir($pkg_dir);
  if(-d "recipes_c-ansi")
   {
    chdir("$pkg_dir/recipes_c-ansi");
    `gmake clean`;
    chdir($pkg_dir);
    `rm -r recipes_c-ansi`;
   }
  `cvs -d \$CESR_CVSROOT co recipes_c-ansi`;
  chdir("./recipes_c-ansi");
  
  `cp ~cesrulib/cesr_libs/packages_cesr_2003_0608_lnx/recipes_c-ansi/recipes/icrc1.c ./recipes/icrc1.c`;

  $cc="cc -std1 -DANSI";
  print `gmake -f makefile_cesr CC="$cc" NRROOT="$pkg_dir/recipes_c-ansi" lib`;
  print `cp librecipes_c-ansi.a ../lib/librecipes_c-ansi.a`;
  print `gmake -f makefile_cesr CC="$cc" NRROOT="$pkg_dir/recipes_c-ansi" clean`;
  print "gmake -f makefile_cesr CC=\"$cc\" NRROOT=\"$pkg_dir/recipes_c-ansi\" CFLAGS=\"-D_ANSI_C_SOURCE -I\$(NRROOT)/include -g\" lib"; 
  print `gmake -f makefile_cesr CC="$cc" NRROOT="$pkg_dir/recipes_c-ansi" CFLAGS="-D_ANSI_C_SOURCE -I$pkg_dir/recipes_c-ansi/include -g" lib`; 
  print `cp librecipes_c-ansi.a ../lib/librecipes_c-ansi_g.a`;
 }
    
  







