#!/usr/bin/perl -w
#-*-perl-*-
#
# this script changes any instances of /disk1/blah or /a/cesr38/cdat/cesr38/disk1/blah in the include file paths to /cdat/cesr38/disk1/blah


foreach $file (@ARGV)
{
  $cesrplatf=`printenv |grep ACC_PLATFORM|cut -d= -f2`;
  chomp $cesrplatf;
  $cesrlib= `printenv |grep ACC_REL`;
  chomp $cesrlib;
  $cesrlib=~s/.*$cesrplatf\///g;
	$file=~s/^-f//;
	$host=`hostname | cut -d. -f1`;
	chomp $host;
	open (F_in, $file) or die("Cannot open file $file\n");
	open (F_out, ">temp.out");
	while(<F_in>)
	 {
		s/ \/disk(.+?)\// \/cdat\/$host\/disk$1\//g;
		s/ \/a\/(.+?)\// \//g;
    s/(?:\s\w\:)??\/\S*\/$cesrlib\/cvssrc\/include/\$\(ACC_INC\)/g;
    s/(?:\s\w\:)??\/\S*\/$cesrlib\/modules/\$\(ACC_MOD\)/g;
    s/(?:\s\w\:)??\/\S*\/$cesrlib\/packages/ \$\(ACC_PKG\)/g;
		print (F_out);
   }
	close(F_in);
	close(F_out);
	rename "temp.out", $file;
 }
