#!/bin/bash
#
# To upgrade local svn directory
# from 1.6 to current svn client
# version.
#

LIST=$(ls -d */)

[ "$(svn upgrade &> /dev/null ; echo $?)" -eq 0 ] || echo "Upgrade not available in this version of svn." || exit 0

for DIR in ${LIST}
do
    echo ${DIR}
    cd ${DIR}
    svn upgrade
    cd ..
done
