!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_svn_version = "53563"
character(*), parameter :: tao_svn_date = "2022-11-17 18:16:09"
end module
