!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_svn_version = "54528"
character(*), parameter :: tao_svn_date = "2023-04-30 04:24:33"
end module
