!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_svn_version = "53495"
character(*), parameter :: tao_svn_date = "2022-11-07 12:24:08"
end module
