&tao_plot_page
	plot_page%size = 400, 400
	plot_page%text_height = 8
	plot_page%n_curve_pts = 5000
/

&tao_params
	global%n_opti_cycles = 100
        global%n_opti_loops = 100
/


&tao_d2_data
  	d2_data%name = 'disp'
  	n_d1_data = 1
/

&tao_d1_data
	ix_d1_data = 1
	datum(1) = 'eta.x' '' '' 'end' 'target' 0 10
	datum(2) = 'deta_ds.x' '' '' 'end' 'target' 0 10
/

&tao_var
	v1_var%name = 'quads'
	var(1:2)%ele_name = "QFR1", "QDR1"
	default_step = 1e-6
	default_attribute = 'k1'
/

