!------------------------------------------------------------------------

&tao_start
  plot_file = '/home/cem52/nfs/CBETA/lattice/tao/tao_plot.init' 
  startup_file = '/home/cem52/nfs/CBETA/lattice/tao/tao.startup'
/

!Beam Initialization
!--------------------------------------------------------
&tao_design_lattice
  n_universes = 1
design_lattice(1)%file = "scott_cell.lat"
  !design_lattice(1)%file = "cell0.lat"
!  design_lattice(1)%file = "cell1.lat"
!  design_lattice(2)%file = "cell2.lat"
!  design_lattice(3)%file = "cell3.lat"
!  design_lattice(4)%file = "cell4.lat"
/

!------------------------------------------------------------------------
&tao_params
  global%plot_on = .true.
  global%track_type = 'single'
  !global%track_type = 'beam'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! quasi or pseudo
  !  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T

    
  ! TEMP for EM field tracking  
  ! bmad_com%abs_tol_tracking = 1e-8
  ! bmad_com%rel_tol_tracking = 1e-8
  /


!------------------------Data--------------------------------------------
!------------------------------------------------------------------------



&tao_d2_data
  d2_data%name = 'floor'
  universe = '*'
  n_d1_data= 1
/
&tao_d1_data
  ix_d1_data= 1
  d1_data%name = "geometry"
  datum( 1) =  "floor.theta"     '' ''  'FF.Mar.END'  'max'   0.340    1e10
  datum( 2) =  "s_position"      ''  '' 'FF.Mar.END'  'max'   0.340    1e10
/



&tao_d2_data
  d2_data%name = 'ele'
  universe = '*'
  n_d1_data= 2
/
&tao_d1_data
  ix_d1_data= 1
  d1_data%name = 'Qua01'
  default_weight = 1
  datum( 1) = 'element_attrib.b1_gradient'     '' ''  'FF.Qua01'  'max'   0.340                  
  datum( 2) = 'element_attrib.x_offset'        '' ''  'FF.Qua01'  'max'   0.340   
/
&tao_d1_data 
  ix_d1_data= 2
  d1_data%name = 'Qua02'
  default_weight = 1
  datum( 1) = 'element_attrib.b1_gradient'     '' ''  'FF.Qua02'  'max'   0.340                  
  datum( 2) = 'element_attrib.x_offset'        '' ''  'FF.Qua02'  'max'   0.340   
/




&tao_d2_data
  d2_data%name = 'ff'
  universe = '*'
  n_d1_data= 4
/

&tao_d1_data
  ix_d1_data= 1
  d1_data%name = 'stability'
  datum( 1) =  'unstable.ring'     '' '' ''  'target'   0.0    1e15
/
&tao_d1_data
    ix_d1_data= 2
	d1_data%name = "orbit"
	default_weight = 1e2
	datum( 1) = 'orbit.x'  '' 'FF.Mar.BEG'  'FF.Mar.END'    'min'   -21e-3
	datum( 2) = 'orbit.x'  '' 'FF.Mar.BEG'  'FF.Mar.END'    'max'    21e-3
/

&tao_d1_data
    ix_d1_data= 3
	d1_data%name = "phasea"
	default_weight = 1
	datum( 1) = 'phase.a'  '' ''  'FF.Mar.END'    'min'   0.314159  ! .05 * 2 pi
	datum( 2) = 'phase.a'  '' ''  'FF.Mar.END'    'max'   3.14159  !  pi
/
&tao_d1_data
    ix_d1_data= 4
	d1_data%name = "phaseb"
	default_weight = 1
	datum( 1) = 'phase.b'  '' ''  'FF.Mar.END'    'min'    0.188496 ! 0.03 * 2 pi   
	datum( 2) = 'phase.b'  '' ''  'FF.Mar.END'    'max'     3.14159  !  pi
/



&tao_d2_data
        d2_data%name = 'tune'
        universe = '*'
        n_d1_data= 1
/
&tao_d1_data
        ix_d1_data= 1
        d1_data%name = 'ab'
        default_weight = 1e6
        datum( 1)%data_type =  'expression: (data::ff.phasea[1]/(2*pi)) '
        datum( 2)%data_type =  'expression: (data::ff.phaseb[1]/(2*pi)) '
        datum( 1:2)%meas = 0.3333333333
        datum( 1:2)%merit_type = 'target'          
/



!&tao_d2_data
        d2_data%name = "nonlinear"
        universe = 1
        n_d1_data= 1
/

!&tao_d1_data
        ix_d1_data= 1
        d1_data%name = "tx66"
        datum( 1) =  "periodic.tt.16"       '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 2) =  "periodic.tt.166"      '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 3) =  "periodic.tt.1666"     '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 4) =  "periodic.tt.16666"    '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 5) =  "periodic.tt.26"       '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 6) =  "periodic.tt.266"      '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 7) =  "periodic.tt.2666"     '' '' 'BEGINNING'  "target"   0.0    1e15
        datum( 8) =  "periodic.tt.26666"    '' '' 'BEGINNING'  "target"   0.0    1e15
/


&tao_d2_data
        d2_data%name = "fmatch"
        universe = '*'
        n_d1_data= 2
/
&tao_d1_data
    ix_d1_data= 1
	d1_data%name = 'beg'
	default_weight = 1e3
	datum( 1) = 'orbit.x'   '' ''   'FF.Mar.BEG'    'target'     0
	datum( 2) = 'orbit.px'  '' ''   'FF.Mar.BEG'    'target'     0
/
&tao_d1_data
    ix_d1_data= 2
	d1_data%name = 'end'
	default_weight = 1e3
	datum( 1) = 'orbit.x'   '' ''   'FF.Mar.END'    'target'     0
	datum( 2) = 'orbit.px'  '' ''   'FF.Mar.END'    'target'     0
/


&tao_d2_data
        d2_data%name = "r56"
        universe = '*'
        n_d1_data= 1
/
&tao_d1_data
    ix_d1_data= 1
	d1_data%name = 'cell'
	default_weight = 1e3
	datum( 1) = 'r56_compaction'   'FF.Mar.BEG' ''   'FF.Mar.END'    'target'     0
/


!-----------Variables--------------

&tao_var 
	v1_var%name = 'begbeam'
	default_universe = '*'
	default_weight = 1e6
	default_step = 1e-4 
  var(1:)%ele_name = 'beam_start', 'beam_start', 'beam_start', 'beam_start' 
  var(1:)%attribute = 'x', 'px', 'pz', 'e_tot'
/  

&tao_var 
	v1_var%name = 'begtwiss'
	default_universe = '*'
	default_weight = 1e6
	default_step = 1e-4 
  var(1:)%ele_name = 'BEGINNING', 'BEGINNING' 
  var(1:)%attribute = 'e_tot', 'alpha_a'
/  
  
  
&tao_var 
	v1_var%name = 'q'
	default_universe = 'gang'
	default_weight = 1e6
	default_step = 1e-4 
  var(1:)%ele_name = 'FF.Qua01',  'FF.Qua02', 'FF.Qua01', 'FF.Qua02'     
  var(1:)%attribute = 'b1_gradient', 'b1_gradient','x_offset', 'x_offset' 
  var(1:)%key_delta = 0.5, 0.5, 0.0002, 0.0002
  var(1:)%low_lim = -20, -20, -.1,-.1
  var(1:)%high_lim = 20,  20,  .1, .1

/




&tao_var 
	v1_var%name = 'edge'
	default_universe = 'gang'
	default_weight = 1e6
	default_step = 1e-4 
  var(1:)%ele_name = 'FF.Qua01', 'FF.Qua02', 'FF.Qua01', 'FF.Qua02'
  var(1:)%attribute = 'fq1', 'fq1', 'fq2', 'fq2'
  var(1:)%key_delta = 1e-4, 1e-4, 1e-6, 1e-6
/	







