#!/bin/sh
svn add ActionInitialization.hpp
svn add DetectorConstruction.hpp
svn add EventAction.hpp
svn add PhysListEmPolarized.hpp
svn add PrimaryGeneratorAction.hpp
svn add RunAction.hpp
svn add StepMax.hpp
svn add SteppingAction.hpp
svn add files
svn add polarized_physics.hpp
