&tao_start
  !plot_file = 'tao_plot.init' 
  !startup_file = 'tao.startup'
/
!Beam Initialization
!--------------------------------------------------------
&tao_design_lattice
  n_universes =1
  design_lattice(1)%file = "lat.bmad"
/

&tao_params
 global%plot_on = False
 global%track_type = 'beam'
/

&tao_beam_init
  beam_init%n_particle = 10
  beam_init%random_engine = 'quasi'
  ix_universe = 1
  !beam0_file = 'beam.in'
  beam_saved_at =  "*"
  beam_init%a_norm_emit = 1.0e-6
  beam_init%b_norm_emit = 1.0e-6
  beam_init%dPz_dz = 0.01
  beam_init%n_bunch = 2    
  beam_init%bunch_charge = 100.0e-12
  beam_init%sig_e = 1e-3
  beam_init%sig_z = 0.001 ! 
/
