!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_version_date = "2025/02/20 23:59:16"
end module
