!+
! Module tao_version_mod
!
! Module is generated by update_tao_version.py.
! Do not modify this file by hand!
!-

module tao_version_mod
character(*), parameter :: tao_version_date = "2024/07/15 21:04:15"
end module
