This initialization file defines how plotting is done.

The following namelist block defines how the plot window (also called
the plot page) is broken up.

&tao_plot_page
  plot_page%size = 400, 500           
  plot_page%text_height = 12.0 
  plot_page%border = 0, 0, 0, 0, '%PAGE'  
  region(1) = 'top'    0.0, 1.0, 0.48, 0.95
  region(2) = 'bottom' 0.0, 1.0, 0.0,  0.48
  place(1) = 'top', 'orbit'
  place(2) = 'bottom', 'phase'
/


&lat_layout_drawing
  ele_shape(1) = 'LCavity::*'       'XBox'      'Red'    40  'none'
  ele_shape(2) = 'Quadrupole::*'    'XBox'  'Magenta'    30  'name'
  ele_shape(3) = 'SBend::*'          'Box'     'Blue'    15  'none'
/

&floor_plan_drawing
  ele_shape(1) = 'LCavity::*'       'XBox'      'Red'    40  'none'
  ele_shape(2) = 'Quadrupole::*'    'XBox'  'Magenta'    30  'name'
  ele_shape(3) = 'SBend::*'          'Box'     'Blue'    15  'none'
/

!----------------------------------------------------------------
Templates define the basics of, say, how to display an orbit.

&tao_template_plot
  plot%name = 'orbit'
  plot%x%min =   0
  plot%x%max = 100
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 2
/

&tao_template_graph
  graph%name = 'x'
  graph_index = 1
  graph%box = 1, 2, 1, 2
  graph%title = 'Horizontal Orbit (mm)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'X'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type   = 'orbit.x'
  curve(1)%y_axis_scale_factor = 1000
  curve(1)%symbol%color = "red"
/

&tao_template_graph
  graph%name = 'y'
  graph_index = 2
  graph%box = 1, 1, 1, 2
  graph%title = 'Vertical Orbit (mm)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'Y'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type   = 'orbit.y'
  curve(1)%y_axis_scale_factor = 1000
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'phase'
  plot%x%min =   0
  plot%x%max = 100
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 2
/

&tao_template_graph
  graph%name = 'a'
  graph_index = 1
  graph%box = 1, 2, 1, 2
  graph%title = 'Horizontal Phase (deg)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'A'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  graph%component = 'model - design'
  curve(1)%data_source = 'data'
  curve(1)%y_axis_scale_factor = 57.29578
/

&tao_template_graph
  graph%name = 'b'
  graph_index = 2
  graph%box = 1, 1, 1, 2
  graph%title = 'Vertical Phase (deg)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'B'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  graph%component = 'model - design'
  curve(1)%data_source = 'data'
  curve(1)%y_axis_scale_factor = 57.29578
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'beta'
  plot%x%min =   0
  plot%x%max = 100
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 2
/

&tao_template_graph
  graph%name = 'a'
  graph_index = 1
  graph%box = 1, 2, 1, 2
  graph%title = 'Horizontal Beta (m)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'A'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type   = 'beta.a'
  curve(1)%y_axis_scale_factor = 1
/

&tao_template_graph
  graph%name = 'b'
  graph_index = 2
  graph%box = 1, 1, 1, 2
  graph%title = 'Vertical Beta (m)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'B'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type   = 'beta.b'
  curve(1)%y_axis_scale_factor = 1
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'eta'
  plot%x%min =   0
  plot%x%max = 100
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 2
/

&tao_template_graph
  graph%name = 'x'
  graph_index = 1
  graph%box = 1, 2, 1, 2
  graph%title = 'Horizontal Eta (m)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'x'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type   = 'eta.x'
/

&tao_template_graph
  graph%name = 'y'
  graph_index = 2
  graph%box = 1, 1, 1, 2
  graph%title = 'Vertical Eta (m)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'Y'
  graph%y%max =  20
  graph%y%min = -20
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%data_type = 'eta.y'
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'cbar'
  plot%x%min =   0
  plot%x%max = 100
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 3
/

&tao_template_graph
  graph%name = '22'
  graph_index = 1
  graph%box = 1, 3, 1, 3
  graph%title = 'Cbar22'
  graph%margin =  0.15, 0.06, 0.2, 0.2, '%BOX'
  graph%y%label = 'Cbar22'
  graph%y%max =  0.10
  graph%y%min = -0.10
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
/

&tao_template_graph
  graph%name = '12'
  graph_index = 2
  graph%box = 1, 2, 1, 3
  graph%title = 'Cbar12'
  graph%margin =  0.15, 0.06, 0.2, 0.2, '%BOX'
  graph%y%label = 'Cbar12'
  graph%y%max =  0.10
  graph%y%min = -0.10
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%y_axis_scale_factor = 1
/

&tao_template_graph
  graph%name = '11'
  graph_index = 3
  graph%box = 1, 1, 1, 3
  graph%title = 'Cbar11'
  graph%margin =  0.15, 0.06, 0.2, 0.2, '%BOX'
  graph%y%label = 'Cbar11'
  graph%y%max =  0.10
  graph%y%min = -0.10
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'data'
  curve(1)%y_axis_scale_factor = 1
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'quad_k1'
  plot%x%min =   0
  plot%x%max = 120
  plot%x%major_div_nominal = 10
  plot%x%label = ' '
  plot%x_axis_type = 'index'
  plot%n_graph = 1
/

&tao_template_graph
  graph%name = 'k1'
  graph_index = 1
  graph%box = 1, 1, 1, 1
  graph%title = 'Quadrupole K1 (1/m^2)'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%label = 'k1'
  graph%y%max =  2
  graph%y%min = -6
  graph%y%major_div = 4
  graph%n_curve = 1
  curve(1)%data_source = 'var_array'
  curve(1)%data_type = 'quad_k1'
  curve(1)%y_axis_scale_factor = 1
/

!----------------------------------------------------------------

&tao_template_plot
  plot%name = 'floor'
  plot%x%min =  -200
  plot%x%max = 200
  plot%n_graph = 1
/

&tao_template_graph
  graph%name = 'this'
	graph%type = 'floor_plan'
  graph_index = 1
  graph%box = 1, 1, 1, 1
  graph%title = 'Floor Plan'
  graph%margin =  0.15, 0.06, 0.12, 0.12, '%BOX'
  graph%y%max =  300
  graph%y%min = -100
/

