#!/bin/sh                                                                                                                   
#                                                                                                                           
# Frontend script to do a Distribution production build, with all build tests/checks enabled.
export DIST_SCRIPT='dist_test_production'
${ACC_ROOT_DIR}/util/Distribution_User_Utility_Wrapper $1

#
