#!/bin/sh                                                                                                                   
#                                                                                                                           
# Frontend script to do a Distribution debug build.
# This script removes the need for symlinks, for Windows builds. 

export DIST_SCRIPT='dist_build_debug'
${ACC_ROOT_DIR}/util/Distribution_User_Utility_Wrapper $1

#
