#!/usr/bin/env python
#-*- python -*-
#

# Compose list of top-level directories in the release that are under
# lab SVN version control.

import sys
import build_mgmt

if len(sys.argv) == 2:
    buildname = sys.argv[1]
else:
    print 'Usage:'
    print ' Accepts a single argument, the name of the release to tag in SVN'


# Does the release exist in all platform directories?
for platform in build_mgmt.platforms:
    
if not build_mgmt.BuildExists(buildname):
    print 'Build does not exist in all supported platform directories.'
    print 'Use command line option "--force" to perform the tag anyway.'
    sys.exit(1)
