"""
Compare quick_plot CSS4 color swatch output against expected CSS4 RGB values.

This script reads the PNG generated by css4_color_swatch.f90 and verifies
that each color patch contains the correct RGB values.

Usage:
    python3 compare_swatches.py css4_qp_swatch.png

Exit code 0 = all colors match, 1 = mismatches found.
"""

import os
import struct
import sys
import zlib


def read_png_pixels(filepath):
    """
    Read a PNG file and return (width, height, pixels).

    Parameters
    ----------
    filepath : str
        Path to PNG file.

    Returns
    -------
    width : int
    height : int
    pixels : list of list of tuple
        pixels[y][x] = (r, g, b)
    """
    with open(filepath, 'rb') as f:
        # Verify PNG signature
        sig = f.read(8)
        assert sig == b'\x89PNG\r\n\x1a\n', "Not a valid PNG file"

        width = height = bit_depth = color_type = None
        idat_data = b''

        while True:
            chunk_len = struct.unpack('>I', f.read(4))[0]
            chunk_type = f.read(4)
            chunk_data = f.read(chunk_len)
            _crc = f.read(4)

            if chunk_type == b'IHDR':
                width, height, bit_depth, color_type = struct.unpack('>IIBB', chunk_data[:10])
                assert bit_depth == 8, f"Only 8-bit PNG supported, got {bit_depth}"
                assert color_type == 2, f"Only RGB PNG supported, got color_type={color_type}"
            elif chunk_type == b'IDAT':
                idat_data += chunk_data
            elif chunk_type == b'IEND':
                break

    # Decompress
    raw = zlib.decompress(idat_data)

    # Parse scanlines (filter byte + RGB pixels)
    pixels = []
    stride = 1 + width * 3  # filter byte + RGB
    for y in range(height):
        offset = y * stride
        filter_byte = raw[offset]
        row_data = raw[offset + 1: offset + stride]

        # Apply filter reconstruction
        if filter_byte == 0:  # None
            pass
        elif filter_byte == 1:  # Sub
            for i in range(3, len(row_data)):
                row_data = row_data[:i] + bytes([(row_data[i] + row_data[i-3]) & 0xFF]) + row_data[i+1:]
        elif filter_byte == 2:  # Up
            if y > 0:
                prev_offset = (y - 1) * stride + 1
                prev_row = raw[prev_offset: prev_offset + width * 3]
                new_row = bytearray(len(row_data))
                for i in range(len(row_data)):
                    new_row[i] = (row_data[i] + prev_row[i]) & 0xFF
                row_data = bytes(new_row)
        # Filters 3 (Average) and 4 (Paeth) not handled for simplicity

        row = []
        for x in range(width):
            r = row_data[x * 3]
            g = row_data[x * 3 + 1]
            b = row_data[x * 3 + 2]
            row.append((r, g, b))
        pixels.append(row)

    return width, height, pixels


def get_expected_colors():
    """Return list of (name, (r, g, b)) in swatch order."""
    # Same order as the Fortran swatch program: original 16, then CSS4 17-154
    script_dir = os.path.dirname(os.path.abspath(__file__))
    expected_file = os.path.join(script_dir, 'css4_reference_swatch_expected.txt')

    colors = []
    with open(expected_file, 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= 5:
                idx = int(parts[0])
                name = parts[1]
                r, g, b = int(parts[2]), int(parts[3]), int(parts[4])
                colors.append((idx, name, (r, g, b)))
    return colors


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <swatch.png>")
        print("  Compares quick_plot swatch against expected CSS4 colors.")
        sys.exit(1)

    png_path = sys.argv[1]
    if not os.path.exists(png_path):
        print(f"Error: {png_path} not found")
        sys.exit(1)

    print(f"Reading swatch: {png_path}")
    width, height, pixels = read_png_pixels(png_path)
    print(f"Image size: {width} x {height}")

    expected = get_expected_colors()
    print(f"Expected colors: {len(expected)}")

    # Determine swatch grid layout
    n_cols = 10
    swatch_w = width // n_cols
    swatch_h = height // ((len(expected) + n_cols - 1) // n_cols)

    print(f"Swatch size: {swatch_w} x {swatch_h} pixels")

    # Sample center pixel of each swatch and compare
    errors = 0
    for seq, (idx, name, (er, eg, eb)) in enumerate(expected):
        col = seq % n_cols
        row = seq // n_cols
        # Sample center of swatch
        cx = col * swatch_w + swatch_w // 2
        cy = row * swatch_h + swatch_h // 2

        if cy >= height or cx >= width:
            print(f"  SKIP index {idx} ({name}): swatch outside image bounds")
            continue

        r, g, b = pixels[cy][cx]

        # Allow tolerance of 1 for rounding
        if abs(r - er) > 1 or abs(g - eg) > 1 or abs(b - eb) > 1:
            print(f"  MISMATCH index {idx:3d} ({name:24s}): "
                  f"got ({r:3d},{g:3d},{b:3d}) expected ({er:3d},{eg:3d},{eb:3d})")
            errors += 1

    print(f"\nResults: {len(expected) - errors}/{len(expected)} colors match")
    if errors > 0:
        print(f"*** {errors} MISMATCHES FOUND ***")
        sys.exit(1)
    else:
        print("*** ALL COLORS MATCH ***")
        sys.exit(0)


if __name__ == '__main__':
    main()
