#!/bin/tcsh

# Script for submitting files to the batch queue which will be run with the
# q.sh script.

setenv buffer1 `echo $PWD | sed 's/^.*\///'`

# Change this to reflect your local jobs directory.
setenv buffer2 "/nfs/acc/user/helms/ctf/jobs/$buffer1"
foreach name ($*)
# Change this to point to your copy of q.sh
    qsub -N $name -v inputfile=$name -v workingdir=$buffer2 /nfs/acc/user/helms/ctf/jobs/q.sh
end

#end
