!------------------------------------------------------------------------

&tao_start
  plot_file = 'tao_plot.init'
/

!------------------------------------------------------------------------

&tao_design_lattice
  n_universes = 1
  design_lattice(1) = "bmad_L9A18A000-_MOVEREC.lat"
  design_lattice(1)%dynamic_aperture_calc = True
/

!------------------------------------------------------------------------

&tao_params
  global%plot_on = T
/


&tao_dynamic_aperture
 da_init(1)%pz = 0, 0.01, 0.015
 da_init(1)%n_angle = 10
 da_init(1)%n_turn = 200 ! This is set low for demonstration purposes.
 da_init(1)%x_init = 0
 da_init(1)%y_init = 0
 da_init(1)%accuracy = 1e-5
/

