#!/bin/bash

# Frontend script to build a package
# Command line must be one of:
#   ./acc_build -production [-cleaner]
#   ./acc_build -production [-test]
#   ./acc_build -debug [-cleaner]
#   ./acc_build -debug [-test]

#set -x

# Run the acc_build_common script
acc_build_common ${1} ${2}
