#ifndef BMAD_PARAMETERS

namespace Bmad {
  const int BMAD_INC_VERSION = 108;
  const int N_ATTRIB_MAXX = 70;
  const int ANTIMUON   = +3;
  const int PROTON     = +2;
  const int POSITRON   = +1;
  const int PHOTON     =  0;
  const int ELECTRON   = -1;
  const int ANTIPROTON = -2;
  const int MUON       = -3;
  const int NOT_LOST = -1;
  const int NOT_SET = -999;
  const int MESH_SURFACE = 1, LINEAR_SURFACE = 2;
  const int HYPER_Y = 1, HYPER_XY = 2, HYPER_X = 3;
  const int SUPER_OK = 0, STALE = 2;
  const int ATTRIBUTE_GROUP = 1, CONTROL_GROUP = 2, FLOOR_POSITION_GROUP = 3;
  const int LENGTH_GROUP = 4, REF_ENERGY_GROUP = 5, MAT6_GROUP = 6;
  const int RAD_INT_GROUP = 7, ALL_GROUPS = 8;
  const int OPAL = 1, IMPACTT = 2;
  const int DRIFT = 1, SBEND = 2, QUADRUPOLE = 3, GROUP = 4;
  const int SEXTUPOLE = 5, OVERLAY = 6, CUSTOM = 7, TAYLOR = 8;
  const int RFCAVITY = 9;
  const int ELSEPARATOR = 10, BEAMBEAM = 11, WIGGLER = 12;
  const int SOL_QUAD = 13, MARKER = 14, KICKER = 15;
  const int HYBRID = 16, OCTUPOLE = 17, RBEND = 18;
  const int MULTIPOLE = 19, ACCEL_SOL = 20;
  const int DEF_BEAM = 21, AB_MULTIPOLE = 22, SOLENOID = 23;
  const int PATCH = 24, LCAVITY = 25, DEF_PARAMETER = 26;
  const int NULL_ELE = 27, INIT_ELE = 28, HOM = 29;
  const int MATCH = 30, MONITOR = 31, INSTRUMENT = 32;
  const int HKICKER = 33, VKICKER = 34, RCOLLIMATOR = 35;
  const int ECOLLIMATOR = 36, GIRDER = 37, BEND_SOL_QUAD = 38;
  const int DEF_BEAM_START = 39, PHOTON_BRANCH = 40;
  const int BRANCH = 41, MIRROR = 42, CRYSTAL = 43;
  const int PIPE = 44, CAPILLARY = 45, MULTILAYER_MIRROR = 46;
  const int E_GUN = 47, EM_FIELD = 48, FLOOR_POSITION = 49;
  const int N_KEY = 49;
  const int N_PART = 2, TAYLOR_ORDER = 3, PARTICLE = 4;
  const int LATTICE_TYPE = 5, SYMMETRY = 6;
  const int VAL1=3, VAL2=4, VAL3=5, VAL4=6, VAL5=7,
          VAL6=9, VAL7=10, VAL8=11, VAL9=12, VAL10=13, VAL11=14,
          VAL12=15;
  const int BETA_A0 = 2, ALPHA_A0 = 3, BETA_B0 = 4,
          ALPHA_B0 = 5, BETA_A1 = 6, ALPHA_A1 = 7, BETA_B1 = 8,
          ALPHA_B1 = 9, DPHI_A = 10, DPHI_B = 11,
          ETA_X0 = 12, ETAP_X0 = 13, ETA_Y0 = 14, ETAP_Y0 = 15,
          ETA_X1 = 16, ETAP_X1 = 17, ETA_Y1 = 18, ETAP_Y1 = 19,
          MATCH_END = 20,
          X0 = 21, PX0 = 22, Y0 = 23, PY0 = 24, Z0 = 25, PZ0 = 26,
          X1 = 27, PX1 = 28, Y1 = 29, PY1 = 30, Z1 = 31, PZ1 = 32,
          MATCH_END_ORBIT = 33, C_11 = 34, C_12 = 35, C_21 = 36, C_22 = 37, GAMMA_C = 39;
  const int X = 1, PX = 2, Y = 3, PY = 4, Z = 5, PZ = 6;
  const int E_FIELD_X = 10,  E_FIELD_Y = 11, PHASE_X = 12, PHASE_Y = 13;
  const int L=1;
  const int TILT=2, COMMAND=2;
  const int TILT_ERR = 3, RF_FREQUENCY=3, DIRECTION=3;
  const int OLD_COMMAND=3, ANGLE=3, KICK=3, X_GAIN_ERR=3;
  const int RF_FREQUENCY_ERR=4, K1=4, SIG_X=4, HARMON=4, H_DISPLACE=4, Y_GAIN_ERR=4;
  const int CRITICAL_ANGLE_FACTOR = 4, TILT_CORR = 4;
  const int LR_FREQ_SPREAD=5, GRAZE_ANGLE=5, K2=5, SIG_Y=5, B_MAX=5, V_DISPLACE=5, CRUNCH=5;
  const int GRADIENT=6, K3=6, SIG_Z=6, NOISE=6;
  const int G=6, GRAZE_ANGLE_IN = 6;
  const int G_ERR=7, VOLTAGE=7, N_POLE=7, BBI_CONST=7, OSC_AMPLITUDE=7;
  const int GRADIENT_ERR=7, CRITICAL_ANGLE = 7;
  const int GRAZE_ANGLE_OUT = 7, IX_BRANCH_TO=7;
  const int RHO=8, DELTA_E=8, GRAZE_ANGLE_ERR = 8;
  const int CHARGE=8, GAP=8, X_GAIN_CALIB=8;
  const int D1_THICKNESS = 9;
  const int KS=9, L_CHORD=9, N_SLICE=9, Y_GAIN_CALIB=9, BRAGG_ANGLE=9;
  const int POLARITY=10, CRUNCH_CALIB=10, ALPHA_ANGLE=10, D2_THICKNESS = 10;
  const int E1=10, E_LOSS=10, DKS_DS=10;
  const int GRAD_LOSS_SR_WAKE=11, S_MIN=11;
  const int E2=11, X_OFFSET_CALIB=11, V1_UNITCELL=11, PSI_ANGLE=11;
  const int S_CENTER=12, Y_OFFSET_CALIB=12, V_UNITCELL=12, V2_UNITCELL=12;
  const int PHI0=13, FINT=13, TILT_CALIB=13, F0_RE=13, F0_RE1=13, S_MAX=13;
  const int PHI0_ERR=14, COEF=14, CURRENT=14, FINTX=14, L_POLE=14;
  const int DE_ETA_MEAS=14, F0_IM=14, F0_IM1 = 14;
  const int QUAD_TILT=15, X_RAY_LINE_LEN=15;
  const int HGAP=15, DPHI0=15, N_SAMPLE=15, FH_RE=15, F0_RE2=15;
  const int HGAPX=16, DPHI0_REF = 16, BEND_TILT=16, FH_IM=16, F0_IM2=16;
  const int DPHI0_MAX=17, H1=17, X_QUAD=17, REF_POLARIZATION=17;
  const int H2=18, Y_QUAD=18, NEGATIVE_GRAZE_ANGLE = 18;
  const int B_PARAM = 19, Z_PATCH=19;
  const int D_SPACING = 20, L_HARD_EDGE = 20;
  const int FIELD_SCALE = 21;
  const int ROLL=22, N_CELL=22;
  const int X_PITCH = 23;
  const int Y_PITCH = 24;
  const int X_OFFSET = 25;
  const int Y_OFFSET = 26;
  const int S_OFFSET = 27, Z_OFFSET = 27;
  const int HKICK = 28, G_TRANS=28, T_OFFSET = 28;
  const int VKICK = 29, C2_CURVE = 29;
  const int BL_HKICK = 30, C3_CURVE = 30;
  const int BL_VKICK = 31, C4_CURVE = 31;
  const int BL_KICK = 32, C2_CURVE_TOT = 32, COUPLER_AT = 32;
  const int B_FIELD = 33, E_FIELD = 33, COUPLER_PHASE = 33, C3_CURVE_TOT = 33;
  const int COUPLER_ANGLE = 34, B_FIELD_ERR = 34, C4_CURVE_TOT = 34;
  const int COUPLER_STRENGTH = 35, D_SOURCE = 35;
  const int B1_GRADIENT = 35, E1_GRADIENT = 35;
  const int B2_GRADIENT = 36, E2_GRADIENT = 36, D_DETEC = 36;
  const int B3_GRADIENT = 37, E3_GRADIENT = 37, TRANSLATE_AFTER = 37, KH_X_NORM = 37;
  const int BS_FIELD = 38, E_TOT_OFFSET = 38, KH_Z_NORM = 38;
  const int DELTA_REF_TIME = 39;
  const int P0C_START = 40;
  const int E_TOT_START = 41;
  const int P0C = 42;
  const int E_TOT = 43;
  const int REF_WAVELENGTH = 44;
  const int X_PITCH_TOT = 45, NO_END_MARKER = 45;
  const int Y_PITCH_TOT = 46;
  const int X_OFFSET_TOT = 47;
  const int Y_OFFSET_TOT = 48;
  const int S_OFFSET_TOT = 49;
  const int TILT_TOT = 50;
  const int N_REF_PASS = 51, REF_CAP_GAMMA = 51;
  const int RADIUS = 52, KH_Y_NORM = 52;
  const int POLE_RADIUS = 53, FOLLOW_DIFFRACTED_BEAM = 53;
  const int DS_FIELD_OFFSET = 54;
  const int THICKNESS = 55, INTEGRATOR_ORDER = 55;
  const int NUM_STEPS = 56, L_X = 56;
  const int DS_STEP = 57, L_Y = 57;
  const int L_Z = 58;
  const int SCRATCH = 59;
  const int GENERAL1 = 60;
  const int GENERAL2 = 61;
  const int GENERAL3 = 62;
  const int X1_LIMIT = 66;
  const int X2_LIMIT = 67;
  const int Y1_LIMIT = 68;
  const int Y2_LIMIT = 69;
  const int CHECK_SUM = 70;
  const int LR_WAKE_FILE = 71, ALPHA_B = 71;
  const int ALIAS =72, ETA_X = 72;
  const int START_EDGE =73, ETA_Y = 73;
  const int END_EDGE =74, ETAP_X = 74;
  const int ACCORDION_EDGE =75, ETAP_Y = 75;
  const int LATTICE = 76, PHI_A = 76, DIFFRACTION_TYPE = 76;
  const int APERTURE_TYPE = 77;
  const int MAP_WITH_OFFSETS = 78, CMAT_11 = 78;
  const int CSR_CALC_ON = 79, CMAT_12 = 79;
  const int SYMMETRIC_EDGE = 80, CMAT_21 = 80;
  const int MAT6_CALC_METHOD = 81, CMAT_22 = 81;
  const int TRACKING_METHOD  = 82, S_LONG = 82;
  const int REF_TIME = 83;
  const int SPIN_TRACKING_METHOD = 84;
  const int APERTURE = 85, RF_AUTO_SCALE_AMP = 85;
  const int X_LIMIT = 86, ABSOLUTE_TIME_TRACKING = 86;
  const int Y_LIMIT = 87, RF_AUTO_SCALE_PHASE = 87;
  const int OFFSET_MOVES_APERTURE = 88, ROOT_BRANCH_NAME = 88;
  const int APERTURE_LIMIT_ON = 89;
  const int SR_WAKE_FILE = 90, ALPHA_A = 90, REF_PATCH = 90;
  const int REF_ORBIT = 91, TERM = 91, USE_PTC_LAYOUT = 91;
  const int X_POSITION = 92, S_SPLINE = 92;
  const int SYMPLECTIFY = 93, Y_POSITION = 93, N_SLICE_SPLINE = 93;
  const int Z_POSITION = 94;
  const int IS_ON = 95, THETA_POSITION = 95;
  const int FIELD_CALC = 96, PHI_POSITION = 96;
  const int PSI_POSITION = 97;
  const int APERTURE_AT = 98, BETA_A = 98;
  const int RAN_SEED = 99, BETA_B = 99;
  const int TO = 100;
  const int FIELD_MASTER = 101;
  const int DESCRIP = 102;
  const int SCALE_MULTIPOLES = 103;
  const int WALL_ATTRIBUTE = 104;
  const int FIELD = 105;
  const int PHI_B = 106, CRYSTAL_TYPE = 106;
  const int TYPE = 107;
  const int SUPERIMPOSE    = 110;
  const int OFFSET         = 111;
  const int REFERENCE      = 112;
  const int ELE_BEGINNING  = 113;
  const int ELE_CENTER     = 114;
  const int ELE_END        = 115;
  const int REF_BEGINNING  = 116;
  const int REF_CENTER     = 117;
  const int REF_END        = 118;
  const int CREATE_EM_FIELD_SLAVE = 119;
  const int A0  = 120, K0L  = 120;
  const int A20 = 140, K20L = 140;
  const int B0  = 150, T0  = 150;
  const int B20 = 170, T20 = 170;
  const int N_ATTRIB_SPECIAL_MAXX = T20;
  const int LINEAR_LATTICE = 10;
  const int CIRCULAR_LATTICE = 12;
  const int FREE = 1, SUPER_SLAVE = 2, OVERLAY_SLAVE = 3;
  const int GROUP_LORD = 4, SUPER_LORD = 5, OVERLAY_LORD = 6;
  const int GIRDER_LORD = 7, MULTIPASS_LORD = 8, MULTIPASS_SLAVE = 9;
  const int NOT_A_LORD = 10, GROUP_SLAVE = 11, PATCH_IN_SLAVE = 12, SLICE_SLAVE = 13;
  const int X_PLANE = 1, Y_PLANE = 2;
  const int Z_PLANE = 3, N_PLANE = 4, S_PLANE = 5;
  const int BMAD_STANDARD = 1, SYMP_LIE_PTC = 2;
  const int RUNGE_KUTTA = 3;
  const int LINEAR = 4, TRACKING = 5, SYMP_MAP = 6;
  const int HARD_EDGE_MODEL = 9, SYMP_LIE_BMAD = 10, STATIC = 11;
  const int BORIS = 12, ADAPTIVE_BORIS = 13, MAD = 14;
  const int TIME_RUNGE_KUTTA = 15, CUSTOM2 = 16;
  const int MAP_TYPE = 1, PERIODIC_TYPE = 3, CONST_REF_ENERGY = 4, NONCONST_REF_ENERGY = 5;
  const int GRID = 2, MAP = 3, REFER_TO_LORDS = 4;
  const int BRAGG = 1, LAUE = 2;
  const int ENTRANCE_END = 1, EXIT_END = 2, BOTH_ENDS = 3;
  const int NO_END = 4, CONTINUOUS = 5, INSIDE = 6, DEAD = 7, OUTSIDE = 8;
  const int LOST = 10;
  const int SINGLE_REF = 1, MATCH_AT_ENTRANCE = 2, MATCH_AT_EXIT = 3;
  const int MATCH_GLOBAL_COORDS = 4, PATCH_IN = 5, PATCH_OUT = 6;
  const int BENDS = 201;
  const int WIGGLERS = 202;
  const int ALL = 203;
  const int RADIANS = 1, DEGREES = 2, CYCLES = 3, KHZ = 4;
  const int ROTATIONALLY_SYMMETRIC_RZ = 1;
  const int IS_LOGICAL = 1, IS_INTEGER = 2, IS_REAL = 3, IS_NAME = 4;
  const int RECTANGULAR = 1, ELLIPTICAL = 2, WALL = 3;
  const int SIGMA_POLARIZATION = 1, PI_POLARIZATION = 2;
  const int N_POLE_MAXX = 20;
  const int S_BLANK   = -1;
  const int S_INFO    = 0;
  const int S_DINFO   = 1;
  const int S_SUCCESS = 2;
  const int S_WARN    = 3;
  const int S_DWARN   = 5;
  const int S_ERROR   = 7;
  const int S_FATAL   = 8;
  const int S_ABORT   = 9;
}

#define BMAD_PARAMETERS
#endif
