&tao_plot_page
	plot_page%size = 400, 400
	plot_page%text_height = 8
	plot_page%n_curve_pts = 5000
/

&tao_d2_data
  	d2_data%name = 'phase_advance'
  	n_d1_data = 1
/

&tao_d1_data
	ix_d1_data = 1
	datum(1) = 'phase.a' '' '' 'end' 'target' 1.5707963267948966 10
	datum(2) = 'phase.b' '' '' 'end' 'target' 1.5707963267948966 10
/

&tao_var
	v1_var%name = 'quads'
	var(1:2)%ele_name = "QFSS", "QDSS"
	default_step = 1e-4
	default_attribute = 'k1'
/
